In [1]:
import pandas as pd

In [2]:
data = pd.read_csv('../madelon/madelon.csv')

In [3]:
X = data.drop("T",axis=1)
X.head()

,at1,at2,at3,at4,at5,at6,at7,at8,at9,at10,...,at491,at492,at493,at494,at495,at496,at497,at498,at499,at500
0,485,477,537,479,452,471,491,476,475,473,...,477,481,477,485,511,485,481,479,475,496
1,483,458,460,487,587,475,526,479,485,469,...,463,478,487,338,513,486,483,492,510,517
2,487,542,499,468,448,471,442,478,480,477,...,487,481,492,650,506,501,480,489,499,498
3,480,491,510,485,495,472,417,474,502,476,...,491,480,474,572,454,469,475,482,494,461
4,484,502,528,489,466,481,402,478,487,468,...,488,479,452,435,486,508,481,504,495,511

In [4]:
y = data[["T"]]
y.head()

   T
0  0
1  0
2  0
3  1
4  1

In [5]:
from sklearn.model_selection import train_test_split

In [6]:
X_train,X_test,y_train,y_test = train_test_split(X,y,stratify=y,test_size=0.2)
X_train,X_validation,y_train,y_validation = train_test_split(X_train,y_train,test_size = 0.2,stratify = y_train)

In [7]:
from sklearn.preprocessing import StandardScaler

In [8]:
scaler = StandardScaler().fit(X_train)
X_train = scaler.transform(X_train)
X_validation = scaler.transform(X_validation)
X_test = scaler.transform(X_test)

In [9]:
X_train = pd.DataFrame(X_train,columns=X.columns)
X_validation = pd.DataFrame(X_validation,columns=X.columns)
X_test = pd.DataFrame(X_test,columns=X.columns)

In [10]:
X_train.to_csv("../madelon/X_train.csv", index=False)
X_validation.to_csv("../madelon/X_validation.csv", index=False)
X_test.to_csv("../madelon/X_test.csv", index=False)

y_train.to_csv("../madelon/y_train.csv", index=False)
y_validation.to_csv("../madelon/y_validation.csv",index = False)
y_test.to_csv("../madelon/y_test.csv", index=False)